- name: Backend 
  hosts: backend 
  become: yes 
  tasks:
  - name: Disable default nodejs module 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enabling Nodejs:20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs 
    ansible.builtin.package:
      name: nodejs 
      state: installed

  - name: Adding expense user 
    ansible.builtin.user:
      name: expense
  
  - name: Downloading the code 
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Creating Director 
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: Unzipping the code 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app 
      remote_src: yes 