- name: Backend 
  hosts: backend 
  become: yes 
  tasks:
  - name: Disable default nodejs module 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enabling Nodejs:20 module
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs 
    ansible.builtin.package:
      name: "{{ item }}" 
      state: installed
    loop:
    - nodejs
    - mysql

  - name: Adding expense user 
    ansible.builtin.user:
      name: expense
  
  - name: Downloading the code 
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Creating Director 
    ansible.builtin.file:
      path: /app 
      state: directory

  - name: Unzipping the code 
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app 
      remote_src: yes 

  - name: Node dependiences installing 
    community.general.npm:
      path: /app 

  - name: Copying the service file 
    ansible.builtin.copy:
      src: backend.service 
      dest: /etc/systemd/system/backend.service

  - name: Installing Python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
  
  - name: import mysql data
    community.mysql.mysql_db:
      state: import 
      name: all
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.manojmantha.online
      target: /app/schema/backend.sql
  